# Generated by Django 3.0.1 on 2020-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_perfect',
            field=models.IntegerField(default=0, verbose_name='信息是否完善'),
        ),
    ]
